# Generated by Django 5.0.4 on 2024-04-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'verbose_name': 'Растение', 'verbose_name_plural': 'Растения'},
        ),
        migrations.AlterField(
            model_name='plant',
            name='height',
            field=models.FloatField(verbose_name='Высота растения (в см)'),
        ),
    ]
